# Generated by Django 5.2.4 on 2025-08-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('userId', 'productId')},
        ),
    ]
