# Generated by Django 5.2.4 on 2025-08-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("placed", "Order Placed"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                ],
                default="placed",
                max_length=10,
            ),
        ),
    ]
